name: DiscordWebhook

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Send to Discord via Action
      uses: nebularg/actions-discord-webhook@master
      with:
        webhook_url: ${{ secrets.B1_SEC }}
      if: always()

    - name: Dump env
      if: always()
      run: set -o posix; set
