name: Discord Webhook

on: [push]

jobs:
  git:
    runs-on: self-hosted
    steps:

    - uses: actions/checkout@v2

    - name: Run Discord Webhook
      uses: johnnyhuy/actions-discord-git-webhook@main
      with:
        censor_username: false
        webhook_url: ${{ secrets.KINGZ_SEC }}